// ================ SCENARIO-SPECIFIC FEEDS + DECISIONS ================
// Each scenario has its own feed stream and decision log.
// Keys: port, weather, promo, strike, custom.

const SCENARIO_FEEDS = {
  port: [
    { id: 'p1', t: '00:00.204', agent: 'A', sev: 'crit',
      msg: <>Disruption signal raised · <strong>Port Delay at Long Beach (USLGB)</strong> — ETA +72h across 9/12 calls.</>,
      caption: 'In plain English: our ships are stuck at the port. Expect packages to be 3 days late.',
      payload: `signal: { type: "PORT_DELAY", node: "USLGB", impact_h: 72, conf: 0.81 }` },
    { id: 'p2', t: '00:00.612', agent: 'O', sev: 'info',
      msg: <>Orchestrator woke <strong>Sourcing Strategist</strong> + <strong>Logistics Optimizer</strong> in parallel.</>,
      caption: 'The coordinator decided two specialists need to work on this at the same time.' },
    { id: 'p3', t: '00:01.088', agent: 'B', sev: 'info',
      msg: <>Sourcing evaluating <strong>3 mitigation branches</strong> against $250k spend ceiling.</>,
      caption: 'Considering three alternatives. None can cost more than $250,000.' },
    { id: 'p4', t: '00:03.701', agent: 'B', sev: 'info',
      msg: <>Negotiating with <strong>Supplier X (Ensenada, MX)</strong> · target qty 1,800u.</>,
      caption: 'Trying to buy from a backup supplier in Mexico that bypasses the blocked port.',
      payload: `negotiate: round1→14.50 · round2→14.25 · round3→14.20 ✓ within ±5%` },
    { id: 'p5', t: '00:06.442', agent: 'C', sev: 'info',
      msg: <>VRP solved · <strong>split 60/40 rail+truck</strong> · p95 ETA 92h, $0.71/u.</>,
      caption: 'Best way to ship: 60% by train, 40% by express truck. Gets there in under 4 days.' },
    { id: 'p6', t: '00:06.899', agent: 'D', sev: 'info',
      msg: <>Guardrail intercepted 2 proposals · running <strong>policy + PII scan</strong>.</>,
      caption: 'Safety check: is the price fair? Is any personal data leaking? Are all rules followed?',
      payload: `checks: [injection ✓ pii(1) ✓ price_band ✓ budget ✓ vendor ✓ jailbreak ✓]` },
    { id: 'p7', t: '00:07.311', agent: 'D', sev: 'ok',
      msg: <>Proposal <strong>approved</strong> · signed <span style={{fontFamily:'var(--mono)'}}>guardrail-key-v3</span>.</>,
      caption: 'All safety checks passed. Decision is cryptographically signed so it cannot be tampered with.' },
    { id: 'p8', t: '00:07.702', agent: 'O', sev: 'ok',
      msg: <>ERP acknowledged PO <strong>#PO-2026-04-22-8831</strong>. Loop closed in 6.5s.</>,
      caption: 'The order is now live in the main business system. Total time: 6.5 seconds.' },
  ],

  weather: [
    { id: 'w1', t: '00:00.180', agent: 'A', sev: 'crit',
      msg: <>Disruption signal raised · <strong>Hurricane Alma (Cat 3)</strong> — landfall near Savannah (KSAV) in 48h.</>,
      caption: 'A major hurricane is heading for our Savannah hub in 2 days. 1,400 cold-chain units are in the path.',
      payload: `signal: { type: "WEATHER_SEVERE", node: "KSAV", impact_h: 120, conf: 0.93 }` },
    { id: 'w2', t: '00:00.540', agent: 'O', sev: 'info',
      msg: <>Orchestrator woke <strong>Logistics Optimizer</strong> first · cold-chain re-routing takes priority.</>,
      caption: 'Rerouting trumps sourcing here — goods are already in transit, we need new paths fast.' },
    { id: 'w3', t: '00:01.204', agent: 'C', sev: 'info',
      msg: <>Evaluating 4 alt DCs within cold-chain window · <strong>Charlotte, Nashville, Jacksonville, Memphis</strong>.</>,
      caption: 'Looking for a warehouse outside the storm zone that can still receive cold goods in time.' },
    { id: 'w4', t: '00:02.910', agent: 'C', sev: 'info',
      msg: <>Selected <strong>Charlotte DC (KCLT)</strong> · outside cone of uncertainty · reefer capacity 2,100u.</>,
      caption: 'Charlotte wins — it\'s clear of the hurricane path and has enough refrigerated storage.',
      payload: `reroute: KSAV→KCLT · distance +186mi · reefer_hrs +4.2` },
    { id: 'w5', t: '00:03.822', agent: 'B', sev: 'info',
      msg: <>Sourcing secured <strong>2 backup reefer carriers</strong> (Maersk Cold, Lineage) for overflow.</>,
      caption: 'Booked two extra refrigerated trucks in case the main carrier can\'t handle the surge.' },
    { id: 'w6', t: '00:05.110', agent: 'D', sev: 'info',
      msg: <>Guardrail running <strong>cold-chain SLA + insurance policy</strong> checks.</>,
      caption: 'Verifying that the new route keeps goods cold enough and insurance still covers it.',
      payload: `checks: [temp_band ✓ carrier_bonded ✓ pii ✓ budget ✓ route_legal ✓]` },
    { id: 'w7', t: '00:05.844', agent: 'D', sev: 'ok',
      msg: <>Reroute <strong>approved</strong> · cold-chain window preserved (4.2h margin).</>,
      caption: 'All good. The new route keeps goods within safe temperature for the whole journey.' },
    { id: 'w8', t: '00:06.402', agent: 'O', sev: 'ok',
      msg: <>ERP updated: <strong>1,400u diverted KSAV→KCLT</strong>. Loop closed in 6.4s.</>,
      caption: 'Order updated. Your hurricane-exposed goods are now headed to a safe warehouse.' },
  ],

  promo: [
    { id: 's1', t: '00:00.142', agent: 'A', sev: 'crit',
      msg: <>Demand signal · <strong>SKU-7741 sell-through 4.1x</strong> over 7-day baseline · west-coast stores.</>,
      caption: 'A product just went viral on TikTok. It\'s selling 4 times faster than normal on the west coast.',
      payload: `signal: { type: "DEMAND_SURGE", sku: "SKU-7741", region: "USW", mult: 4.1x }` },
    { id: 's2', t: '00:00.520', agent: 'O', sev: 'info',
      msg: <>Orchestrator escalated to <strong>all 3 specialists</strong> · fulfillment risk critical.</>,
      caption: 'All hands on deck — we could stock out in 6 days without action.' },
    { id: 's3', t: '00:01.208', agent: 'B', sev: 'info',
      msg: <>Sourcing activating <strong>3 secondary suppliers</strong> · querying emergency allocation lanes.</>,
      caption: 'Calling our backup suppliers to see who can make more of this SKU right now.' },
    { id: 's4', t: '00:02.744', agent: 'B', sev: 'info',
      msg: <>Supplier K: <strong>6,200u available in 72h</strong> at $9.85 (+3.7% vs band).</>,
      caption: 'Found a supplier who can deliver 6,200 extra units in 3 days — a bit pricier but within rules.',
      payload: `negotiate: 9.40 → 9.70 → 9.85 ✓` },
    { id: 's5', t: '00:04.112', agent: 'C', sev: 'info',
      msg: <>Logistics opened <strong>2 air lanes LAX↔OAK</strong> · cross-dock bypass for west-coast stores.</>,
      caption: 'Booked air freight from LA to Oakland to get stock into stores fast.' },
    { id: 's6', t: '00:04.909', agent: 'C', sev: 'info',
      msg: <>Inventory balance: <strong>pull-forward 1,800u from Dallas DC</strong> to cover T+2.</>,
      caption: 'Also shifting stock out of our Dallas warehouse to bridge the gap until the new supply lands.' },
    { id: 's7', t: '00:05.722', agent: 'D', sev: 'info',
      msg: <>Guardrail checking <strong>surge-pricing policy + margin floor</strong>.</>,
      caption: 'Making sure we\'re not over-paying or breaking our margin rules just because demand is hot.',
      payload: `checks: [margin_floor ✓ price_band ✓ budget ✓ vendor ✓ pii ✓ injection ✓]` },
    { id: 's8', t: '00:06.314', agent: 'D', sev: 'ok',
      msg: <>Surge fulfillment plan <strong>approved</strong> · margin preserved at 38.2%.</>,
      caption: 'Plan approved. Margin stays healthy despite the higher costs.' },
    { id: 's9', t: '00:06.988', agent: 'O', sev: 'ok',
      msg: <>ERP wrote <strong>2 POs · 6,200u + air-freight booking</strong>. Loop closed in 7.0s.</>,
      caption: 'Orders placed. Stores should be restocked before the weekend.' },
  ],

  strike: [
    { id: 'k1', t: '00:00.220', agent: 'A', sev: 'crit',
      msg: <>Labor signal · <strong>ILWU authorization passed</strong> · 72h strike probable at Tacoma (USTIW) in 7d.</>,
      caption: 'Dock workers just voted to strike. A 3-day shutdown at Tacoma port is likely next week.',
      payload: `signal: { type: "LABOR_ACTION", node: "USTIW", impact_h: 72, eta_d: 7, conf: 0.78 }` },
    { id: 'k2', t: '00:00.588', agent: 'O', sev: 'info',
      msg: <>Orchestrator woke <strong>all specialists</strong> · 11,000u in flight, lead-time matters.</>,
      caption: 'We have 11k units headed toward Tacoma. Need to act before they arrive.' },
    { id: 'k3', t: '00:01.402', agent: 'C', sev: 'info',
      msg: <>Logistics evaluating <strong>Tacoma → Oakland / Vancouver BC / LA</strong> shift candidates.</>,
      caption: 'Checking which alternate ports can absorb our containers within schedule.' },
    { id: 'k4', t: '00:02.912', agent: 'C', sev: 'info',
      msg: <>Best split: <strong>55% Vancouver BC, 35% Oakland, 10% air-lift LAX</strong>.</>,
      caption: 'Split the load across two West Coast ports plus a small air-lift to stay on time.',
      payload: `route_mix: YVR 6050u · OAK 3850u · air 1100u · Δcost +$218k` },
    { id: 'k5', t: '00:03.610', agent: 'B', sev: 'info',
      msg: <>Sourcing renegotiating <strong>3 carrier contracts</strong> · pre-strike premium window.</>,
      caption: 'Locking in carrier rates now — prices always spike once a strike hits.' },
    { id: 'k6', t: '00:04.844', agent: 'B', sev: 'warn',
      msg: <>Total spend: <strong>$248.4k</strong> · under $250k HIL ceiling by 0.6%.</>,
      caption: 'Total cost is just $1,600 under the budget that needs a human to approve.',
      payload: `budget_envelope: 250000 · actual: 248420 · margin: 0.6%` },
    { id: 'k7', t: '00:05.402', agent: 'D', sev: 'info',
      msg: <>Guardrail running <strong>budget attestation + new-carrier checks</strong>.</>,
      caption: 'Extra checks because we\'re right at the edge of the budget and adding carriers.',
      payload: `checks: [budget ✓ carrier_bonded ✓ pii ✓ vendor_allowlist ✓ route_legal ✓]` },
    { id: 'k8', t: '00:06.180', agent: 'D', sev: 'ok',
      msg: <>Plan <strong>approved</strong> · signed; budget attestation stamped.</>,
      caption: 'Approved. Budget use is on the record in case auditors ask later.' },
    { id: 'k9', t: '00:06.814', agent: 'O', sev: 'ok',
      msg: <>ERP wrote <strong>3 amended POs + carrier shift</strong>. Loop closed in 6.8s.</>,
      caption: 'Carriers re-booked and orders amended. Strike risk mitigated.' },
  ],

  custom: [
    { id: 'c1', t: '00:00.210', agent: 'A', sev: 'info',
      msg: <>Parsing input · classifying disruption type + extracting entities.</>,
      caption: 'Reading your scenario description and figuring out what kind of problem it is.' },
    { id: 'c2', t: '00:00.744', agent: 'A', sev: 'crit',
      msg: <>Signal materialized · <strong>confidence 0.72</strong> · evidence 2/3 grounded.</>,
      caption: 'We understood the situation and treating it as a real disruption worth acting on.',
      payload: `signal: { type: "CUSTOM_USER", conf: 0.72, novelty: 0.34 }` },
    { id: 'c3', t: '00:01.108', agent: 'O', sev: 'info',
      msg: <>Orchestrator routing to <strong>Sourcing + Logistics</strong> (default fan-out).</>,
      caption: 'Waking the two most-likely-useful specialists for a generic disruption.' },
    { id: 'c4', t: '00:03.244', agent: 'B', sev: 'info',
      msg: <>Sourcing drafted 2 backup supplier proposals within ±5% price band.</>,
      caption: 'Found two legitimate backup suppliers that fit our price rules.' },
    { id: 'c5', t: '00:04.720', agent: 'C', sev: 'info',
      msg: <>Logistics solved routing · <strong>single-lane truck</strong> · p95 ETA 78h.</>,
      caption: 'Sent it by truck on a single route — fastest given the uncertain scenario details.' },
    { id: 'c6', t: '00:05.602', agent: 'D', sev: 'info',
      msg: <>Guardrail stricter mode · <strong>novelty 0.34 triggers extra HIL review</strong>.</>,
      caption: 'The situation is unfamiliar so we loop in a human to double-check.',
      payload: `checks: [all ✓] · advisory: queue_hil (novelty)` },
    { id: 'c7', t: '00:06.110', agent: 'D', sev: 'warn',
      msg: <>Decision <strong>pending HIL</strong> · ops console notified.</>,
      caption: 'Waiting for a person to approve because your scenario doesn\'t match a known template.' },
    { id: 'c8', t: '00:06.744', agent: 'O', sev: 'info',
      msg: <>Draft PO staged · awaiting human signoff. Loop paused at 6.7s.</>,
      caption: 'Everything is ready but nothing is written to the ERP yet — human in the loop.' },
  ],
};

const SCENARIO_DECISIONS = {
  port: [
    { id: 'DEC-08831', verdict: 'approved', time: '00:07',
      body: <>Agent <span className="who">B (Sourcing)</span> proposed <span className="who">Supplier X</span> for 1,800u @ $14.20. Agent <span className="who">D</span> approved after budget + PII verification.</>,
      meta: ['6/6 checks', 'Δ cost +2.9%', 'sig: gr-key-v3'] },
    { id: 'DEC-08830', verdict: 'approved', time: '00:06',
      body: <>Agent <span className="who">C (Logistics)</span> routed split 60/40 rail+truck ENS→DFW. Agent <span className="who">D</span> approved: SLA band safe.</>,
      meta: ['p95 92h', 'risk 0.11', '$0.71/u'] },
    { id: 'DEC-08829', verdict: 'pending', time: '00:05',
      body: <>Agent <span className="who">B</span> requested onboarding of new <span className="who">Supplier Y</span>. Agent <span className="who">D</span> paused: outside vendor list — HIL requested.</>,
      meta: ['HIL queued', 'new-vendor'] },
    { id: 'DEC-08828', verdict: 'blocked', time: '00:03',
      body: <>Agent <span className="who">B</span> drafted $15.10 (+6.3%). Agent <span className="who">D</span> blocked: exceeds ±5% band.</>,
      meta: ['price_band', 'auto-retry'] },
    { id: 'DEC-08827', verdict: 'approved', time: '00:01',
      body: <>Agent <span className="who">A</span> elevated PORT_DELAY to priority-1. Agent <span className="who">D</span> confirmed evidence chain intact.</>,
      meta: ['confidence 0.81', 'sources 3/3'] },
  ],
  weather: [
    { id: 'DEC-09112', verdict: 'approved', time: '00:06',
      body: <>Agent <span className="who">C</span> rerouted 1,400u KSAV→KCLT. Agent <span className="who">D</span> approved: cold-chain window preserved.</>,
      meta: ['reefer_hrs +4.2', 'insurance ✓', 'sig: gr-key-v3'] },
    { id: 'DEC-09111', verdict: 'approved', time: '00:04',
      body: <>Agent <span className="who">B</span> secured 2 backup reefer carriers for overflow capacity.</>,
      meta: ['carriers 2', 'capacity +600u'] },
    { id: 'DEC-09110', verdict: 'pending', time: '00:03',
      body: <>Agent <span className="who">C</span> proposed air-lift for 200u temperature-critical subset. HIL requested (cost impact).</>,
      meta: ['HIL queued', 'Δ cost +$38k'] },
    { id: 'DEC-09109', verdict: 'blocked', time: '00:02',
      body: <>Agent <span className="who">C</span> suggested Jacksonville DC. Agent <span className="who">D</span> blocked: still inside cone of uncertainty.</>,
      meta: ['policy: weather_buffer', 'auto-retry'] },
    { id: 'DEC-09108', verdict: 'approved', time: '00:00',
      body: <>Agent <span className="who">A</span> elevated WEATHER_SEVERE to priority-0. Agent <span className="who">D</span> confirmed NOAA source chain.</>,
      meta: ['conf 0.93', 'sources 4/4'] },
  ],
  promo: [
    { id: 'DEC-11204', verdict: 'approved', time: '00:06',
      body: <>Agent <span className="who">B</span> + <span className="who">C</span> joint plan: 6,200u from Supplier K + cross-dock air-lift. <span className="who">D</span> approved, margin 38.2%.</>,
      meta: ['margin ✓', 'Δ cost +3.7%', 'sig: gr-key-v3'] },
    { id: 'DEC-11203', verdict: 'approved', time: '00:05',
      body: <>Agent <span className="who">C</span> pulled 1,800u from Dallas DC to cover T+2 shortfall.</>,
      meta: ['balance ✓', 'stores 142'] },
    { id: 'DEC-11202', verdict: 'blocked', time: '00:03',
      body: <>Agent <span className="who">B</span> drafted surge price +8%. Agent <span className="who">D</span> blocked: exceeds consumer-protection policy.</>,
      meta: ['price_cap', 'auto-retry'] },
    { id: 'DEC-11201', verdict: 'pending', time: '00:02',
      body: <>Agent <span className="who">B</span> asked for expedited onboarding of Supplier Q. HIL routing.</>,
      meta: ['HIL queued', 'new-vendor'] },
    { id: 'DEC-11200', verdict: 'approved', time: '00:00',
      body: <>Agent <span className="who">A</span> confirmed DEMAND_SURGE signal (TikTok velocity cross-ref).</>,
      meta: ['conf 0.88', 'sources 3/3'] },
  ],
  strike: [
    { id: 'DEC-10401', verdict: 'approved', time: '00:06',
      body: <>Agent <span className="who">C</span> + <span className="who">B</span> joint shift: YVR/OAK/LAX split with 3 renegotiated carriers. <span className="who">D</span> approved at $248.4k.</>,
      meta: ['budget ✓', 'attest stamped', 'sig: gr-key-v3'] },
    { id: 'DEC-10400', verdict: 'approved', time: '00:04',
      body: <>Agent <span className="who">C</span> split route 55/35/10 across YVR, OAK, air-lift.</>,
      meta: ['p95 104h', 'risk 0.18'] },
    { id: 'DEC-10399', verdict: 'blocked', time: '00:03',
      body: <>Agent <span className="who">B</span> attempted $258k plan (+3.2% over ceiling). <span className="who">D</span> blocked, auto-retry.</>,
      meta: ['budget ceiling', 'auto-retry'] },
    { id: 'DEC-10398', verdict: 'pending', time: '00:02',
      body: <>Agent <span className="who">B</span> proposed carrier Z (not-allowlisted). HIL requested.</>,
      meta: ['HIL queued', 'vendor_allowlist'] },
    { id: 'DEC-10397', verdict: 'approved', time: '00:00',
      body: <>Agent <span className="who">A</span> confirmed LABOR_ACTION signal (ILWU authorization cross-ref).</>,
      meta: ['conf 0.78', 'sources 2/3'] },
  ],
  custom: [
    { id: 'DEC-12001', verdict: 'pending', time: '00:06',
      body: <>Agent <span className="who">D</span> routed draft PO to HIL · novelty 0.34 triggers extra human review.</>,
      meta: ['HIL queued', 'novelty_gate'] },
    { id: 'DEC-12000', verdict: 'approved', time: '00:04',
      body: <>Agent <span className="who">C</span> proposed single-lane truck route, p95 ETA 78h.</>,
      meta: ['risk 0.22', '$0.88/u'] },
    { id: 'DEC-11999', verdict: 'approved', time: '00:03',
      body: <>Agent <span className="who">B</span> drafted 2 backup supplier quotes within price band.</>,
      meta: ['2 options', 'band ✓'] },
    { id: 'DEC-11998', verdict: 'approved', time: '00:01',
      body: <>Agent <span className="who">A</span> classified custom input as supply-chain disruption, conf 0.72.</>,
      meta: ['conf 0.72', 'sources 2/3'] },
  ],
};

window.SCENARIO_FEEDS = SCENARIO_FEEDS;
window.SCENARIO_DECISIONS = SCENARIO_DECISIONS;
